# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: Install Node.js
- script: |
    npm install
  displayName: Install Dependencies
- script: |
    npm run download-edge
    pwd
  displayName: Downloading And Extracting Edge Zip (Windows x64)
- script: |
    export EDGE_CHROMIUM_PATH=$(Build.Repository.LocalPath)/out/edge/src
    export EDGE_CHROMIUM_OUT_DIR=Release
    npm run build
  displayName: Building
- script: |
    export EDGE_CHROMIUM_PATH=$(Build.Repository.LocalPath)/out/edge/src
    export EDGE_CHROMIUM_OUT_DIR=Release
    npm run test
  displayName: Linting and Testing
- script: |
    export EDGE_CHROMIUM_PATH=$(Build.Repository.LocalPath)/out/edge/src
    export EDGE_CHROMIUM_OUT_DIR=Release
    npm run package
  displayName: Creating .vsix
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'